###################error########################


タルトフリゼットは,タルトは香ばしくて美味しかったですが，苺のコンポートが粘度の高い苺ジャムのように感じてしまって,少し残念な感じに^_^;

バニーユは,初めて食べたバニラメインのケーキですが，苦味も含めて非常に美味しいです 
 list index out of range
Traceback (most recent call last):
  File "/root/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/blist.py", line 43, in __init__
    self._setPAS(juman_format)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/blist.py", line 79, in _setPAS
    tag.pas = Pas(tag.tag_id, self)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/pas.py", line 87, in __init__
    self.__set_args(tag_predicate.features.get("項構造"), CaseInfoFormat.PASv41)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/pas.py", line 186, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/pas.py", line 181, in __parse_case_analysis_items
    yield self.__parse_case_info_format(items, case_info_format)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/pas.py", line 145, in __parse_case_info_format
    eid = int(items[3])
IndexError: list index out of range
###########################################
###################error########################
店内にて
ル　シュープレーム
コーヒー

お持ち帰り
パン　ド　セイグル　ノア　レザン

クロワッサン　ダマンド
パンドゥミ　コンプレ　フロマージュハート

時間がよかったのか、ゆっくり座って楽しめた 
 'utf-8' codec can't decode byte 0xe3 in position 754: invalid continuation byte
Traceback (most recent call last):
  File "/root/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/knp.py", line 82, in parse
    knp_lines = self.subprocess.query(juman_str, pattern=r'^%s$'%(self.pattern))
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/juman/process.py", line 70, in query
    line = self.stdouterr.readline().rstrip().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 754: invalid continuation byte
###########################################
###################error########################

すぐに大好きなお店になった 
 list index out of range
Traceback (most recent call last):
  File "/root/workspace/NLPLibrary/nlplib_pyknp2.py", line 307, in pyknp_make_commentlist
    result = kparser.parse(sentence)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/knp.py", line 83, in parse
    return BList(knp_lines, self.pattern, juman_format)
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/blist.py", line 41, in __init__
    self._set_parent_child()
  File "/root/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pyknp/knp/blist.py", line 164, in _set_parent_child
    bnst.parent = self._bnst[bnst.parent_id]
IndexError: list index out of range
###########################################
